#!/bin/bash

################################################################################
# Multi-Cloud GPU Terraform Deployment Wrapper
# 
# This script provides a simplified interface for deploying GPU infrastructure
# to AWS, Azure, or GCP with automatic NVIDIA driver and CUDA installation.
#
# Usage: ./deploy.sh
################################################################################

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TERRAFORM_DIR="$SCRIPT_DIR"

# Cleanup on exit
cleanup() {
  if [ $? -ne 0 ]; then
    echo -e "${RED}✗ Deployment failed!${NC}"
  fi
}
trap cleanup EXIT

################################################################################
# Helper Functions
################################################################################

print_header() {
  echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
  echo -e "${BLUE}$1${NC}"
  echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
}

print_success() {
  echo -e "${GREEN}✓ $1${NC}"
}

print_error() {
  echo -e "${RED}✗ $1${NC}"
}

print_info() {
  echo -e "${YELLOW}ℹ $1${NC}"
}

prompt_with_default() {
  local prompt="$1"
  local default="$2"
  local input
  
  read -p "$prompt [$default]: " input
  echo "${input:-$default}"
}

validate_cloud_provider() {
  case "$1" in
    aws|azure|gcp)
      return 0
      ;;
    *)
      print_error "Invalid cloud provider. Must be: aws, azure, or gcp"
      return 1
      ;;
  esac
}

validate_aws_region() {
  # AWS supports these regions for GPU instances
  local region="$1"
  case "$region" in
    ap-south-1|ap-south-2|us-east-1|us-west-2|eu-west-1)
      return 0
      ;;
    *)
      print_info "Using custom region: $region (verify g5.4xlarge availability)"
      return 0
      ;;
  esac
}

validate_azure_region() {
  # Common Azure regions
  local region="$1"
  case "$region" in
    eastus|westus|westus2|eastus2|southcentralus|centralus|northeurope|westeurope)
      return 0
      ;;
    *)
      print_info "Using custom region: $region (verify Standard_NV36ads_A10_v5 availability)"
      return 0
      ;;
  esac
}

validate_gcp_region() {
  # GCP regions with GPU availability
  local region="$1"
  case "$region" in
    us-central1|us-west1|us-east1|europe-west1|asia-east1)
      return 0
      ;;
    *)
      print_info "Using custom region: $region (verify g2-standard-16 availability)"
      return 0
      ;;
  esac
}

check_terraform() {
  if ! command -v terraform &> /dev/null; then
    print_error "Terraform is not installed. Please install Terraform first."
    echo "Visit: https://www.terraform.io/downloads"
    exit 1
  fi
  
  local tf_version=$(terraform version | head -n 1)
  print_success "Found $tf_version"
}

check_terraform_files() {
  local required_files=("main.tf" "variables.tf" "outputs.tf" "providers.tf")
  
  for file in "${required_files[@]}"; do
    if [ ! -f "$TERRAFORM_DIR/$file" ]; then
      print_error "Required file not found: $file"
      exit 1
    fi
  done
  
  print_success "All Terraform files found"
}

initialize_terraform() {
  print_info "Initializing Terraform..."
  cd "$TERRAFORM_DIR"
  terraform init -upgrade
  print_success "Terraform initialized"
}

validate_terraform() {
  print_info "Validating Terraform configuration..."
  cd "$TERRAFORM_DIR"
  terraform validate
  print_success "Terraform configuration is valid"
}

create_tfvars() {
  local cloud_provider="$1"
  local region="$2"
  local vm_name="$3"
  local ssh_key="$4"
  local project_id="$5"
  local git_username="$6"
  local git_password="$7"
  
  local tfvars_file="$TERRAFORM_DIR/terraform.tfvars"
  
  cat > "$tfvars_file" << EOF
# Auto-generated by deploy.sh
# Generated: $(date)

cloud_provider = "$cloud_provider"
region         = "$region"
vm_name        = "$vm_name"
git_username   = "$git_username"
git_password   = "$git_password"
EOF

  case "$cloud_provider" in
    aws)
      echo "aws_certificate_arn = null" >> "$tfvars_file"
      ;;
    azure)
      if [ -n "$ssh_key" ]; then
        echo "azure_ssh_public_key = \"$ssh_key\"" >> "$tfvars_file"
      fi
      ;;
    gcp)
      if [ -n "$project_id" ]; then
        echo "gcp_project_id = \"$project_id\"" >> "$tfvars_file"
      fi
      ;;
  esac
  
  print_success "Created terraform.tfvars"
}

show_plan() {
  print_info "Generating Terraform plan..."
  cd "$TERRAFORM_DIR"
  terraform plan -no-color | tee /tmp/deploy_plan.txt
}

confirm_deployment() {
  echo ""
  read -p "Do you want to apply this plan? (yes/no): " confirm
  
  if [ "$confirm" != "yes" ]; then
    print_info "Deployment cancelled"
    exit 0
  fi
}

apply_terraform() {
  print_info "Applying Terraform configuration..."
  cd "$TERRAFORM_DIR"
  terraform apply -auto-approve
  print_success "Infrastructure deployed successfully!"
}

show_outputs() {
  print_header "Deployment Outputs"
  
  cd "$TERRAFORM_DIR"
  terraform output -json 2>/dev/null | jq . || true
}

show_next_steps() {
  local cloud_provider="$1"
  
  echo ""
  print_header "🎉 Deployment Initiated - Single Click Setup Active!"
  
  echo ""
  print_success "✓ Terraform applied successfully"
  print_success "✓ Cloud-init will auto-configure everything"
  print_success "✓ No manual setup required!"
  
  echo ""
  print_header "⏱️  Installation Timeline (35-50 minutes total)"
  echo "  1. Instance boot                     (2-5 min)"
  echo "  2. NVIDIA drivers + CUDA             (10-15 min)"
  echo "  3. Node.js v18 installation          (2-3 min)"
  echo "  4. OAN UI Service deployment         (5-10 min)"
  echo "  5. Jenkins installation              (5-10 min)"
  echo "  6. Jenkins auto-configuration        (5-10 min)"
  echo "     • Admin user created"
  echo "     • Plugins installed"
  echo "     • Pipeline job created"
  
  echo ""
  print_header "📋 What's Being Auto-Configured"
  echo "  ✓ NVIDIA Driver 550 + CUDA 12.4"
  echo "  ✓ Node.js v18 from NodeSource"
  echo "  ✓ OAN UI Service (React + Vite) - Port 5000"
  echo "  ✓ Agri Help (with Git credentials) - Port 3000"
  echo "  ✓ Nginx reverse proxy (ports 5000, 3000)"
  echo "  ✓ Jenkins CI/CD server (port 8080)"
  echo "  ✓ Jenkins admin user (admin/admin123)"
  echo "  ✓ Jenkins pipeline job (oan-ui-service)"
  
  echo ""
  print_header "🔍 Monitor Installation Progress"
  
  case "$cloud_provider" in
    aws)
      INSTANCE_IP=\$(cd \$TERRAFORM_DIR && terraform output -raw aws_instance_public_ip 2>/dev/null || echo '<instance-ip>')
      LB_URL=\$(cd \$TERRAFORM_DIR && terraform output -raw aws_http_endpoint 2>/dev/null || echo '<load-balancer-url>')
      echo "  SSH Command:"
      echo "    ssh -i <your-key.pem> ubuntu@\$INSTANCE_IP"
      ;;
    azure)
      INSTANCE_IP=\$(cd \$TERRAFORM_DIR && terraform output -raw azure_vm_public_ip 2>/dev/null || echo '<instance-ip>')
      LB_URL=\$(cd \$TERRAFORM_DIR && terraform output -raw azure_http_endpoint 2>/dev/null || echo '<load-balancer-url>')
      echo "  SSH Command:"
      echo "    ssh -i <your-key> azureuser@\$INSTANCE_IP"
      ;;
    gcp)
      INSTANCE_IP=\$(cd \$TERRAFORM_DIR && terraform output -raw gcp_instance_public_ip 2>/dev/null || echo '<instance-ip>')
      LB_URL=\$(cd \$TERRAFORM_DIR && terraform output -raw gcp_http_endpoint 2>/dev/null || echo '<load-balancer-url>')
      echo "  SSH Command:"
      echo "    gcloud compute ssh <instance-name> --zone=<zone>"
      ;;
  esac
  
  echo ""
  echo "  Monitor Cloud-Init:"
  echo "    sudo tail -f /var/log/cloud-init-output.log"
  echo ""
  echo "  Check Deployment Status:"
  echo "    cat /opt/deployment-info.txt"
  
  echo ""
  print_header "🌐 Access URLs (after installation completes)"
  echo "  Application:      \$LB_URL"
  echo "  Health Check:     \$LB_URL:5000/health"
  echo "  Jenkins:          http://\$INSTANCE_IP:8080"
  
  echo ""
  print_header "🔐 Jenkins Credentials (Auto-Created)"
  echo "  Username:  admin"
  echo "  Password:  admin123"
  echo ""
  echo "  View on instance:"
  echo "    cat /opt/jenkins-credentials.txt"
  
  echo ""
  print_header "🚀 Quick Start - Jenkins Pipeline"
  echo "  1. Wait 35-50 minutes for installation"
  echo "  2. Open Jenkins: http://\$INSTANCE_IP:8080"
  echo "  3. Login with: admin / admin123"
  echo "  4. Click 'oan-ui-service' job"
  echo "  5. Click 'Build Now' to deploy"
  echo ""
  echo "  Pipeline will:"
  echo "    • Clone repo from GitHub"
  echo "    • Run tests with coverage"
  echo "    • Build production artifacts"
  echo "    • Deploy to /opt/applications/"
  echo "    • Restart Nginx"
  echo "    • Verify health check"
  
  echo ""
  print_header "⚙️  Optional: GitHub Webhook (Auto-Deploy)"
  echo "  To enable automatic builds on push:"
  echo "  1. Go to: https://github.com/the-swag-coder/oan-ui-service/settings/hooks"
  echo "  2. Add webhook: http://\$INSTANCE_IP:8080/github-webhook/"
  echo "  3. Content type: application/json"
  echo "  4. Events: Just the push event"
  
  echo ""
  print_header "✅ Verification Commands"
  echo "  # Check if installation is complete"
  echo "  grep -i 'Final deployment report completed' /var/log/cloud-init-output.log"
  echo ""
  echo "  # View deployment report"
  echo "  cat /opt/deployment-info.txt"
  echo ""
  echo "  # Verify NVIDIA drivers"
  echo "  nvidia-smi"
  echo ""
  echo "  # Verify OAN UI Service"
  echo "  curl http://localhost:5000/health"
  echo ""
  echo "  # Verify Agri Help"
  echo "  curl http://localhost:3000/health"
  echo ""
  echo "  # Verify Jenkins"
  echo "  curl http://localhost:8080/login"
  echo ""
  echo "  # View deployment report"
  echo "  cat /opt/deployment-info.txt"
  
  echo ""
  print_header "📚 Documentation"
  echo "  Complete guides available in readme/ folder:"
  echo "    • JENKINS_QUICK_START.md"
  echo "    • CI-CD_PIPELINE_WORKFLOW.md"
  echo "    • APP_DEPLOYMENT_GUIDE.md"
  
  echo ""
  print_success "🎊 Single-Click Deployment Initiated!"
  echo ""
  echo "  Everything is being configured automatically."
  echo "  Just wait 35-50 minutes and your complete"
  echo "  GPU server with CI/CD will be ready!"
  echo ""
      echo "   nvidia-smi"
      echo ""
      echo "Load Balancer IP:"
      echo "   $(cd $TERRAFORM_DIR && terraform output -raw gcp_load_balancer_ip 2>/dev/null || echo 'See outputs above')"
      ;;
  esac
  
  echo ""
  echo "To destroy the infrastructure:"
  echo "  cd $TERRAFORM_DIR && terraform destroy"
}

################################################################################
# Main Script
################################################################################

main() {
  print_header "Multi-Cloud GPU Terraform Deployment"
  
  # Check prerequisites
  print_info "Checking prerequisites..."
  check_terraform
  check_terraform_files
  
  # Prompt for configuration
  echo ""
  print_header "Configuration"
  
  # Cloud provider selection
  while true; do
    cloud_provider=$(prompt_with_default "Cloud provider (aws/azure/gcp)" "aws")
    if validate_cloud_provider "$cloud_provider"; then
      break
    fi
  done
  
  # Region selection
  case "$cloud_provider" in
    aws)
      region=$(prompt_with_default "AWS region" "ap-south-1")
      validate_aws_region "$region"
      ;;
    azure)
      region=$(prompt_with_default "Azure region" "eastus")
      validate_azure_region "$region"
      ;;
    gcp)
      region=$(prompt_with_default "GCP region" "us-central1")
      validate_gcp_region "$region"
      ;;
  esac
  
  # VM name
  vm_name=$(prompt_with_default "VM/Instance name" "gpu-server")
  
  # Git credentials for private repositories
  echo ""
  print_header "Git Credentials (for Private Repositories)"
  print_info "If you need to deploy private repositories, provide credentials."
  print_info "Otherwise, leave empty for public repositories only."
  echo ""
  
  read -p "Git username/email (leave empty if not needed): " git_username
  if [ -n "$git_username" ]; then
    read -s -p "Git password/token: " git_password
    echo ""
    print_success "Git credentials saved (will be securely passed to instances)"
  else
    git_password=""
    print_info "Skipping Git credentials - will only deploy public repositories"
  fi
  
  # Cloud-specific prompts
  ssh_key=""
  project_id=""
  
  if [ "$cloud_provider" = "azure" ]; then
    echo ""
    print_info "Enter your SSH public key (leave empty to use placeholder):"
    read -p "SSH public key: " ssh_key
  fi
  
  if [ "$cloud_provider" = "gcp" ]; then
    echo ""
    project_id=$(prompt_with_default "GCP Project ID" "")
  fi
  
  # Initialize and validate
  print_header "Initialization"
  initialize_terraform
  
  echo ""
  validate_terraform
  
  # Create terraform.tfvars
  echo ""
  create_tfvars "$cloud_provider" "$region" "$vm_name" "$ssh_key" "$project_id" "$git_username" "$git_password"
  
  # Show plan
  echo ""
  show_plan
  
  # Confirm and apply
  echo ""
  confirm_deployment
  
  apply_terraform
  
  # Show outputs
  echo ""
  show_outputs
  
  # Show next steps
  show_next_steps "$cloud_provider"
  
  print_success "Deployment script completed!"
}

# Run main function
main "$@"
